In [83]:
import pandas as pd
import sys
import os
import plotly.graph_objects as go
import plotly.express as px
import plotly.io as pio
pio.renderers.default = "iframe"

# Agregar la carpeta calibration_code al path
sys.path.append(os.path.abspath("../../calibration_code"))

# Ahora puedes importar los módulos personalizados
from modelling_tools import plot_histogram, plot_univariate_freq
from utils import g, describe_dataset, format_number
from config import get_data_path, get_code_path
from data_cleaning import check_dataframe_quality

# <font color = 'red'> ANÁLISIS UNIVARIADO

## <font color = 'darkblue'> OBJETIVO

Analizar el comportamiento individual de las variables y detectar errores en los datos.

## <font color = 'darkblue'> METODOLOGÍA

El análisis univariado se realiza de manera independiente para cada variable con el objetivo de comprender su distribución y comportamiento dentro del conjunto de datos. 

Se diferencian dos tipos de variables en el análisis, aplicando metodologías específicas para cada caso.

* Variables Categóricas:

    - Se analiza la distribución de frecuencias de cada categoría dentro de la variable. 
    - Para las variables categóricas se utiliza la regla de dedo del 5%:  
    se agrupan todas aquellas categorías que individualmente pesen menos que el 5% del total de observaciones, 
    con el fin de que el modelo no aprenda patrones débiles o pocos representativos. 
    Muchas categorías con pocos datos puede sobreajustarse a casos muy particulares.
    

* Variables Continuas:

    - Se estudia la distribución de los valores mediante histogramas y gráficos de densidad.
    - Se calculan medidas estadísticas clave, como la media, mediana, desviación estándar, mínimo y máximo.
    - Se analizan posibles asimetrías en la distribución y la presencia de valores atípicos.

# <font color = 'red'> GENERALIDADES

In [84]:
df = pd.read_csv(get_data_path("Credit_score_cleaned_data.csv"))

In [85]:
res = check_dataframe_quality(df, verbose = False)

In [86]:
num_rows, num_cols = df.shape

s = {'Fuente de los datos':'https://www.kaggle.com/code/ayushsharma0812/credit-score-classification-part-1-data-cleaning/notebook',
     'Número de filas': format_number(num_rows),
     'Número de variables': format_number(num_cols - 1),
     'Categorías de la variable dependiente': ', '.join(df['Credit_Score'].unique()),
     'Número de clientes únicos': format_number(len(df['Customer_ID'].unique())),
     'Valores faltantes':res['Missing values'],
     'Valores infinitos':res['Infinite values'],
     'Filas Duplicadas':res['Duplicate rows']}

describe_dataset(s, separator_length=125)

-----------------------------------------------------------------------------------------------------------------------------
Fuente de los datos: https://www.kaggle.com/code/ayushsharma0812/credit-score-classification-part-1-data-cleaning/notebook
-----------------------------------------------------------------------------------------------------------------------------
Número de filas: 100,000
-----------------------------------------------------------------------------------------------------------------------------
Número de variables: 31
-----------------------------------------------------------------------------------------------------------------------------
Categorías de la variable dependiente: Standard, Good, Poor
-----------------------------------------------------------------------------------------------------------------------------
Número de clientes únicos: 12,500
-----------------------------------------------------------------------------------------------------------------------------
Valores faltantes: 0
-----------------------------------------------------------------------------------------------------------------------------
Valores infinitos: 0
-----------------------------------------------------------------------------------------------------------------------------
Filas Duplicadas: 0
-----------------------------------------------------------------------------------------------------------------------------

# <font color = 'red'> ANÁLISIS DE LAS VARIABLES

## <font color = 'darkblue'> AGE

Las edades van desde los 14 a los 56 años.

La distribución de las edades es relativamente simétrica: la media y la mediana son iguales, prácticamente.

Es raro deudores con tan poca edad.

In [87]:
fig = plot_histogram(df = df, column='Age', figsize = (800, 500))
fig.show()

In [88]:
g(df[['Age']].describe(percentiles=[0.15, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]).transpose(), 0)

       count mean std min 15% 25% 50% 75% 90% 95% 99% max
Age  100,000   33  11  14  21  24  33  42  48  52  55  56

# <font color = 'darkblue'> OCCUPATION

La ocupación es una variable categórica con valores como 'Teacher', 'Engineer', 'Doctor', 'Lawyer', entre otros. 

Todas las categorías de esta variable pesan más que el 5%.

In [89]:
fig = plot_univariate_freq(df, 'Occupation', figsize=(900, 500), title=None, normalize=True)
fig.show()

# <font color = 'darkblue'> ANNUAL_INCOME

La distribución de los ingresos anuales tiene una forma típica: 

presenta una asimetría positiva (sesgo a la derecha), donde la mediana es menor que el promedio. 

Esto indica que hay menos casos de deudores con altos ingresos en comparación con aquellos que tienen ingresos más bajos.

Los ingresos anuales oscilan desde los 7 mil a los 180 mil aproximadamente.

La mediana de los ingresos anuales es de 37 mil.

In [90]:
fig = plot_histogram(df, 'Annual_Income', figsize=(900, 500))
fig.show()

In [91]:
g(df[['Annual_Income']].describe(percentiles=[0.15, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]).transpose(), 0)

,count,mean,std,min,15%,25%,50%,75%,90%,95%,99%,max
Annual_Income,"100,000","50,505","38,299","7,006","15,950","19,343","37,000","71,683","108,786","130,290","166,892","179,987"

# <font color = 'darkblue'> MONTHLY_INHAND_SALARY

El salario mensual en mano va desde los 304 a los 15,000 dólares. 

La distribución del salario mensual es asimétrica, con una mayor concentración en los valores más bajos.

In [92]:
plot_histogram(df, 'Monthly_Inhand_Salary', figsize=(900, 500))

In [93]:
g(df[['Monthly_Inhand_Salary']].describe(percentiles=[0.15, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]).transpose(), 0)

,count,mean,std,min,15%,25%,50%,75%,90%,95%,99%,max
Monthly_Inhand_Salary,"100,000","4,199","3,187",304,"1,312","1,627","3,096","5,962","9,122","10,834","13,831","15,205"

# <font color = 'darkblue'> NUM_BANK_ACCOUNTS

El número de cuentas bancarias va desde 0 a 11. 

La distribución del número de cuentas bancarias es relativamente simétrica, con una media alrededor de 5.

In [94]:
plot_univariate_freq(df, 'Num_Bank_Accounts', figsize=(900, 500), normalize=True)

In [95]:
g(df[['Num_Bank_Accounts']].describe(percentiles=[0.15, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]).transpose(), 0)

                     count mean std min 15% 25% 50% 75% 90% 95% 99% max
Num_Bank_Accounts  100,000    5   3   0   3   3   5   7   9  10  10  11

# <font color = 'darkblue'> NUM_CREDIT_CARD

El número de tarjetas de crédito va desde 0 a 11. 

La distribución del número de tarjetas de crédito es relativamente simétrica, con una media alrededor de 6.

In [96]:
plot_univariate_freq(df, 'Num_Credit_Card', figsize=(900, 500), normalize=True)

In [97]:
g(df[['Num_Credit_Card']].describe(percentiles=[0.15, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]).transpose(), 0)

                   count mean std min 15% 25% 50% 75% 90% 95% 99% max
Num_Credit_Card  100,000    6   2   0   3   4   5   7   8   9  10  11

# <font color = 'darkblue'> INTEREST_RATE

Las tasas de interés van desde el 1% al 34%. 

La distribución de la tasa de interés es relativamente simétrica, pero hay tasas de interés muy bajas, lo cual es raro.

In [98]:
fig = plot_histogram(df, 'Interest_Rate', figsize=(900, 500))
fig.show()

In [99]:
g(df[['Interest_Rate']].describe(percentiles=[0.15, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]).transpose(), 0)

                 count mean std min 15% 25% 50% 75% 90% 95% 99% max
Interest_Rate  100,000   15   9   1   5   7  13  20  28  31  34  34

# <font color = 'darkblue'> NUM_OF_LOAN

El número de préstamos va desde 0 a 9. La distribución del número de préstamos es relativamente simétrica, con una media de 4.

In [100]:
plot_univariate_freq(df, 'Num_of_Loan', figsize=(900, 500), normalize=True)

In [101]:
g(df[['Num_of_Loan']].describe(percentiles=[0.15, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]).transpose(), 0)

               count mean std min 15% 25% 50% 75% 90% 95% 99% max
Num_of_Loan  100,000    4   2   0   1   2   3   5   7   8   9   9

# <font color = 'darkblue'> DELAY_FROM_DUE_DATE

El retraso desde la fecha de vencimiento va desde -5 a 76 días. El 90% de los casos llega a lo sumo a 45.

In [102]:
plot_histogram(df, 'Delay_from_due_date', figsize=(900, 500))

In [103]:
g(df[['Delay_from_due_date']].describe(percentiles=[0.15, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]).transpose(), 0)

                       count mean std min 15% 25% 50% 75% 90% 95% 99% max
Delay_from_due_date  100,000   21  15  -5   7  10  18  28  45  54  61  67

# <font color = 'darkblue'> NUM_OF_DELAYED_PAYMENT

El número de pagos retrasados oscila entre 0 y 28 pagos. Con una media alrededor de 13.

In [104]:
plot_univariate_freq(df, 'Num_of_Delayed_Payment', figsize=(900, 500), normalize=True)

In [105]:
g(df[['Num_of_Delayed_Payment']].describe(percentiles=[0.15, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]).transpose(), 0)

                          count mean std min 15% 25% 50% 75% 90% 95% 99% max
Num_of_Delayed_Payment  100,000   13   6   0   6   9  14  18  21  23  25  28

# <font color = 'darkblue'> CHANGED_CREDIT_LIMIT

Los cambios porcentaules en los límietes de crédito oscilan entre 0 y 28%.

El cambio porcentual promedio es de 13%, mientras que el cambio porcentual mediano es de 14%.

In [106]:
plot_histogram(df, 'Changed_Credit_Limit', figsize=(900, 500))

In [107]:
g(df[['Changed_Credit_Limit']].describe(percentiles=[0.15, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]).transpose(), 0)

                        count mean std min 15% 25% 50% 75% 90% 95% 99% max
Changed_Credit_Limit  100,000   10   7  -6   3   5   9  15  19  24  29  37

# <font color = 'darkblue'> CREDIT_MIX

Corresponde a la variable dependiente

Las categorías son: 'Good', 'Average', 'Bad'. 

Los malos pesan un 23.77%.

In [108]:
plot_univariate_freq(df, 'Credit_Mix', figsize=(900, 500), normalize = True)

# <font color = 'darkblue'> OUTSTANDING_DEBT

La deuda pendiente va desde 0.23 a casi 5000 dólares. La distribución del Saldo pendiente tiene una asimetría positiva

In [109]:
plot_histogram(df, 'Outstanding_Debt', figsize=(900, 500))

In [110]:
g(df[['Outstanding_Debt']].describe(percentiles=[0.15, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]).transpose(), 2)

,count,mean,std,min,15%,25%,50%,75%,90%,95%,99%,max
Outstanding_Debt,"100,000.00","1,426.22","1,155.13",0.23,348.16,566.07,"1,166.15","1,945.96","3,189.07","4,073.76","4,806.97","4,998.07"

# <font color = 'darkblue'> CREDIT_UTILIZATION_RATIO

La tasa de utilización del crédito oscila entre 20% y 50%. Es relativamente simétrica: la utilización promedio y mediana es de alrededor del 32%.

In [111]:
plot_histogram(df, 'Credit_Utilization_Ratio', figsize=(900, 500))

In [112]:
g(df[['Credit_Utilization_Ratio']].describe(percentiles=[0.15, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]).transpose(), 2)

,count,mean,std,min,15%,25%,50%,75%,90%,95%,99%,max
Credit_Utilization_Ratio,"100,000.00",32.29,5.12,20.00,26.28,28.05,32.31,36.50,39.04,40.22,42.45,50.00

# <font color = 'darkblue'> CREDIT_HISTORY_AGE

La antiguedad del cliente como deudor oscila de 1 a 404 meses. El promedio es de 221 meses (18 años aprox.)

In [113]:
plot_histogram(df, 'Credit_History_Age', figsize=(900, 500))

In [114]:
g(df[['Credit_History_Age']].describe(percentiles=[0.15, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]).transpose(), 2)

,count,mean,std,min,15%,25%,50%,75%,90%,95%,99%,max
Credit_History_Age,"100,000.00",221.21,99.68,1.00,104.00,144.00,219.00,302.00,362.00,381.00,396.00,404.00

# <font color = 'darkblue'> PAYMENT_OF_MIN_AMOUNT

El pago del monto mínimo es una variable categórica con valores 'Yes' y 'No'.

Aproximadamente el 40% de los clientes no paga el monto mínimo.

In [115]:
plot_univariate_freq(df, 'Payment_of_Min_Amount', figsize=(900, 600), normalize=True)

# <font color = 'darkblue'> TOTAL_EMI_PER_MONTH

Los montos de las cuotas oscilan de -1 a 357 dólares. El promedio de USD 88

In [116]:
plot_histogram(df, 'Total_EMI_per_month', figsize=(900, 500))

In [117]:
g(df[['Total_EMI_per_month']].describe(percentiles=[0.15, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]).transpose(), 2)

,count,mean,std,min,15%,25%,50%,75%,90%,95%,99%,max
Total_EMI_per_month,"100,000.00",88.21,83.24,-1.00,10.26,25.59,61.54,131.53,217.71,264.31,330.58,357.41

# <font color = 'darkblue'> AMOUNT_INVESTED_MONTHLY

El monto del cliente invertido mensualmente se distribuye con una fuerte asimetría positiva.

Oscila de 0 a 2.000 dólares.

El monto mediano es de 194 dólares, mientras que el promedio es de 193 dólares.

In [118]:
plot_histogram(df, 'Amount_invested_monthly', figsize=(900, 500))

In [119]:
g(df[['Amount_invested_monthly']].describe(percentiles=[0.15, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]).transpose(), 2)

,count,mean,std,min,15%,25%,50%,75%,90%,95%,99%,max
Amount_invested_monthly,"100,000.00",193.69,194.79,0.00,54.39,73.73,129.36,234.35,426.45,597.70,978.90,"1,977.33"

# <font color = 'darkblue'> PAYMENT_BEHAVIOUR

Todas las categorías sobre el comportamiento del cliente tienen pesos superiores al 5%:

La categoría más riesgosa debería ser la de alto gasto con pagos pequeños, la cual pesa un 20.81%, esto se
podría corroborar en el análisis bivariado.

In [120]:
plot_univariate_freq(df, 'Payment_Behaviour', figsize=(900, 600), normalize=True)

# <font color = 'darkblue'> MONTHLY_BALANCE

El balance mensual va desde 0 a 1,600 dólares. 

La distribución del balance mensual es asimétrica, con una mayor concentración en los valores más bajos.

In [121]:
plot_histogram(df, 'Monthly_Balance', figsize=(900, 600))

In [122]:
g(df[['Monthly_Balance']].describe(percentiles=[0.15, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]).transpose(), 0)

,count,mean,std,min,15%,25%,50%,75%,90%,95%,99%,max
Monthly_Balance,"100,000",403,214,0,242,270,337,472,711,864,"1,139","1,602"

# <font color = 'darkblue'> LAST_LOAN

En Last_Loan_1, Last_Loan_2 y Last_Loan_3, todas las categorías distintas de "No Loan" representan más del 5% del total.

En Last_Loan_4, la categoría con menor peso es 4.72%, cerca del umbral del 5%.

A partir de Last_Loan_5, todas las categorías distintas de "No Loan" pesan menos del 4%, agravándose cada vez más, de tal forma que, en Last_Loan_9, las categorías distintas de "No Loan" tienen una representatividad menor al 0.52%.

Posible interpretación:

A medida que avanzamos en el historial de préstamos anteriores (Last_Loan_5 en adelante), la mayoría de los clientes ya no tienen un préstamo 
registrado, lo que podría indicar una menor relevancia de estos datos más antiguos para predecir el comportamiento actual.
La disminución progresiva de las categorías distintas de "No Loan" sugiere que los datos más recientes (Last_Loan_1 - Last_Loan_3) son más 
representativos del comportamiento crediticio actual del cliente.

Decisión metodológica
no considerar Last_Loan_5 en adelante

In [123]:
for i in range(1, 10):
    fig = plot_univariate_freq(df, f'Last_Loan_{i}', figsize=(900, 600), normalize=True)
    fig.show()
    print('\n')